spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm552425
    password: 140904

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false

server:
  port: 80

